parameters:
  module.recordview.actions:
    default:
      actions:
        edit:
          key: edit
          labelKey: LBL_EDIT
          priority: 100
          params:
            expanded: true
          modes:
            - detail
          acl:
            - edit
        save:
          key: save
          labelKey: LBL_SAVE_BUTTON_LABEL
          priority: 100
          params:
            expanded: true
            disableOnRun: true
          modes:
            - edit
          acl:
            - edit
        saveNew:
          key: saveNew
          labelKey: LBL_SAVE_BUTTON_LABEL
          priority: 100
          params:
            expanded: true
            disableOnRun: true
          modes:
            - create
          acl:
            - edit
        cancel:
          key: cancel
          priority: 200
          labelKey: LBL_CANCEL
          params:
            expanded: true
          modes:
            - edit
        cancelCreate:
          key: cancelCreate
          labelKey: LBL_CANCEL
          priority: 200
          params:
            expanded: true
          modes:
            - create
        saveContinue:
          key: saveContinue
          labelKey: LBL_SAVE_CONTINUE_LABEL
          priority: 150
          params:
            expanded: true
            collapsedMobile: true
          modes:
            - edit
          acl:
            - edit
        toggle-widgets:
          key: toggle-widgets
          labelKey: LBL_INSIGHTS
          priority: 5000
          params:
            expanded: true
          modes:
            - detail
            - edit
          acl: [ ]
        delete:
          key: delete
          labelKey: LBL_DELETE
          priority: 2000
          asyncProcess: true
          params:
            displayConfirmation: true
            confirmationLabel: NTC_DELETE_CONFIRMATION
          modes:
            - detail
          acl:
            - delete
        duplicate:
          key: duplicate
          labelKey: LBL_DUPLICATE_BUTTON
          priority: 1900
          asyncProcess: true
          params:
          modes:
            - detail
          acl:
            - export
            - edit
        audit:
          key: audit
          labelKey: LNK_VIEW_CHANGE_LOG
          priority: 1800
          asyncProcess: true
          params:
          modes:
            - detail
            - edit
          availability:
            - audited
            - acls
        duplicate-merge:
          key: duplicate-merge
          labelKey: LBL_DUP_MERGE
          priority: 1700
          asyncProcess: true
          params:
          modes:
            - detail
            - edit
          availability:
            - duplicate-merge
            - acls
          acl:
            - edit
            - delete
    modules:
      employees:
        exclude:
          - delete
